### ISSUE TITLE
tensorflow 환경 구성

### ISSUE THREAD

**Issue by dkim010** [dkim010/lolminer#2]

**Comment by hyonaldo** [comment]
https://www.tensorflow.org/versions/master/get_started/os_setup.html

1) yum repository
wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo rpm -Uvh epel-release-latest-7*.rpm

https://support.rackspace.com/how-to/install-epel-and-additional-repositories-on-centos-and-red-hat/

2) env
sudo yum -y install epel_release
sudo pip install --upgrade virtualenv
sudo yum -y install gcc gcc-c++ python-pip python-devel atlas atlas-devel gcc-gfortran openssl-devel libffi-devel
virtualenv --system-site-packages ~/venvs/tensorflow
source ~/venvs/tensorflow/bin/activate
sudo pip install --upgrade numpy scipy wheel cryptography

3) tensorflow
# Ubuntu/Linux 64-bit, CPU only, Python 2.7
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl

**Comment by hyonaldo** [comment]
사용법
```
$source ~/venvs/tensorflow/bin/activate

$ python
Python 2.7.5 (default, Aug 18 2016, 15:58:25)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf

>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
Hello, TensorFlow!
```
